
---
- name: Installer les outils de sécurité
  hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Mettre à jour le cache APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer les outils de sécurité
      ansible.builtin.apt:
        name:
          - nmap
          - nikto
          - lynis
        state: present 